language: go

branches:
  only:
    - master
    - develop
    - /^sprint.*$/

matrix:
  include:
    - os: osx
      osx_image: xcode10
      go: "1.11"
      before_install:
        - brew install rocksdb
        - brew install git-lfs
        - git lfs install
        - brew tap alecthomas/homebrew-tap
        - brew install gometalinter
      before_script:
        - git lfs pull
      script:
        - make build
        - make lint
        - make test
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - os: linux
      dist: trusty
      go: "1.11"
      services:
        - docker
      before_install:
        - docker pull iostio/iost-dev:1.0.0
        - git lfs install
      before_script:
        - git lfs pull
      script:
        - docker run -it --rm -v $(pwd):/gopath/src/github.com/iost-official/go-iost iostio/iost-dev:1.0.0 make build
        - docker run -it --rm -v $(pwd):/gopath/src/github.com/iost-official/go-iost iostio/iost-dev:1.0.0 make lint
        - docker run -it --rm -v $(pwd):/gopath/src/github.com/iost-official/go-iost iostio/iost-dev:1.0.0 make test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
